/**
 * Cross-turn, vendor-portable memory (the headline requirement): a directive
 * given at turn 1 is recalled and injected at turn 20 — regardless of which model
 * generated the intervening turns — because the memory layer never touches a
 * model. Also exercises real code/doc corpus ingestion and semantic recall.
 */

import { describe, it, expect } from "vitest";

import { InProcessStore } from "../../src/exec/store.js";
import { buildBasicPlugins } from "../../src/plugins/index.js";
import { absorbText } from "../../src/handlers/memory.js";
import { assembleRecall, recallBlock } from "../../src/exec/recall.js";
import type { MemoryPlugin } from "../../src/plugins/interfaces.js";

/** One conversation turn: who spoke and the text. `vendor` is metadata only —
 *  memory ingestion ignores it, which is the whole point. */
interface Turn {
  speaker: "user" | "assistant";
  vendor?: "claude" | "openai" | "local";
  text: string;
}

/** Ingest a turn: record it for semantic recall, and absorb user directives/facts.
 *  Model-independent — `vendor` never enters the stator. */
async function ingest(memory: MemoryPlugin, turn: Turn): Promise<void> {
  await memory.recordTurn(turn.text);
  if (turn.speaker === "user") await memory.write(absorbText(turn.text, "user"), { tick: 0 });
}
async function ingestAll(memory: MemoryPlugin, turns: Turn[]): Promise<void> {
  for (const t of turns) await ingest(memory, t);
}

/** A realistic 20-turn coding conversation: a standing directive up front, then a
 *  mix of code, docs, and facts, generated by different vendors along the way. */
const CONVERSATION: Turn[] = [
  { speaker: "user", vendor: "claude", text: "Always use tabs for indentation, and always cite your sources." },
  { speaker: "assistant", vendor: "claude", text: "Understood — tabs for indentation, and I'll cite sources." },
  { speaker: "user", vendor: "claude", text: "My name is Ada. My project is called Rotor." },
  { speaker: "assistant", vendor: "claude", text: "Nice to meet you, Ada. I'll keep the Rotor project in mind." },
  { speaker: "user", vendor: "claude", text: "Here is our config parser:\nfunction parseConfig(path) {\n\treturn JSON.parse(readFileSync(path));\n}" },
  { speaker: "assistant", vendor: "claude", text: "That parseConfig reads and JSON-parses the file at path." },
  { speaker: "user", vendor: "openai", text: "Add error handling to the database connection pool in pool.ts." },
  { speaker: "assistant", vendor: "openai", text: "I wrapped the pool.connect call in a try/catch and added a retry." },
  { speaker: "user", vendor: "openai", text: "The auth service uses JWT tokens with a 15 minute expiry." },
  { speaker: "assistant", vendor: "openai", text: "Noted: JWT auth, 15 minute token expiry." },
  { speaker: "user", vendor: "openai", text: "Write unit tests for the config parser using vitest." },
  { speaker: "assistant", vendor: "openai", text: "Added vitest tests covering valid, missing, and malformed config files." },
  { speaker: "user", vendor: "openai", text: "Our deploy target is Kubernetes with a HorizontalPodAutoscaler." },
  { speaker: "assistant", vendor: "openai", text: "Got it — k8s deploy with an HPA." },
  { speaker: "user", vendor: "local", text: "Refactor the logger to emit structured JSON lines." },
  { speaker: "assistant", vendor: "local", text: "The logger now emits one JSON object per line." },
  { speaker: "user", vendor: "local", text: "Never log secrets or tokens, ever." },
  { speaker: "assistant", vendor: "local", text: "I'll make sure secrets and tokens are never logged." },
  { speaker: "user", vendor: "local", text: "What was the shape of our config parser again?" },
  { speaker: "assistant", vendor: "local", text: "It's parseConfig(path) → JSON.parse(readFileSync(path))." },
];

function freshMemory() {
  return buildBasicPlugins({ store: new InProcessStore() }).memory;
}

describe("standing directives survive across turns (mode 1)", () => {
  it("recalls a turn-1 directive at turn 20", async () => {
    const memory = freshMemory();
    await ingestAll(memory, CONVERSATION);

    // Turn 20's query shares NO words with the directive — similarity would miss it.
    const ctx = await assembleRecall(memory, "write a function to parse a config file", { entity: "user" });
    const directives = ctx.directives.join(" | ").toLowerCase();
    expect(directives).toContain("tabs");
    expect(directives).toContain("cite");
    // A later directive from a different vendor's turn is there too.
    expect(directives).toContain("never log secrets");
  });

  it("de-duplicates a restated directive but keeps distinct ones", async () => {
    const memory = freshMemory();
    await ingest(memory, { speaker: "user", text: "Always use tabs for indentation." });
    await ingest(memory, { speaker: "user", text: "Always use tabs for indentation." }); // restated
    await ingest(memory, { speaker: "user", text: "Always write tests first." });
    const ctx = await assembleRecall(memory, "", { entity: "user" });
    expect(ctx.directives).toHaveLength(2);
  });
});

describe("vendor portability", () => {
  it("recall is identical regardless of which vendor generated the turns", async () => {
    // Same conversation, but every turn relabeled to a single vendor.
    const asClaude = freshMemory();
    await ingestAll(asClaude, CONVERSATION.map((t) => ({ ...t, vendor: "claude" as const })));
    const asLocal = freshMemory();
    await ingestAll(asLocal, CONVERSATION.map((t) => ({ ...t, vendor: "local" as const })));

    const q = "how do I parse the config file";
    const a = recallBlock(await assembleRecall(asClaude, q, { entity: "user" }));
    const b = recallBlock(await assembleRecall(asLocal, q, { entity: "user" }));
    expect(a).toBe(b); // memory never depended on the vendor
    expect(a).toContain("Standing instructions");
  });
});

describe("structured facts + semantic recall (modes 1 & 2)", () => {
  it("recalls user self-facts stored earlier (my X is Y → user's slot)", async () => {
    const memory = freshMemory();
    await ingestAll(memory, CONVERSATION);
    const name = (await memory.executeOp("lookup", { person: "user", slot: "name" })).rows;
    const project = (await memory.executeOp("lookup", { person: "user", slot: "project" })).rows;
    expect(name[0]?.filler).toBe("Ada");
    expect(project[0]?.filler).toBe("Rotor");
  });

  it("surfaces the earlier config-parser turn for a keyword-overlapping query", async () => {
    const memory = freshMemory();
    await ingestAll(memory, CONVERSATION);
    const ctx = await assembleRecall(memory, "config parser parseConfig JSON.parse", { entity: "user", topK: 3, threshold: 0.05 });
    const joined = ctx.recalled.map((h) => h.text).join(" ");
    expect(joined).toContain("parseConfig");
  });
});
